// IPL 2026 Player Database
// Only players confirmed available (injuries/withdrawals excluded)
// Roles: BAT, BOWL_FAST, BOWL_SPIN, AR, WK
// Tiers: MARQUEE (base 200+), MID (base 100-150), UNCAPPED (base 50)

const PLAYER_DB = [
  // ── BATTERS ──────────────────────────────────────────────
  {id:1,  name:"Virat Kohli",         team:"RCB", role:"BAT", tier:"MARQUEE", base:300, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:2,  name:"Rohit Sharma",        team:"MI",  role:"BAT", tier:"MARQUEE", base:250, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:3,  name:"Shubman Gill",        team:"GT",  role:"BAT", tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:4,  name:"Shreyas Iyer",        team:"PBKS",role:"BAT", tier:"MARQUEE", base:250, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:5,  name:"Yashasvi Jaiswal",    team:"RR",  role:"BAT", tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:6,  name:"Travis Head",         team:"SRH", role:"BAT", tier:"MARQUEE", base:200, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:7,  name:"Ruturaj Gaikwad",     team:"CSK", role:"BAT", tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:8,  name:"Rajat Patidar",       team:"RCB", role:"BAT", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:9,  name:"Riyan Parag",         team:"RR",  role:"BAT", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:10, name:"Suryakumar Yadav",    team:"MI",  role:"BAT", tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:11, name:"Tilak Varma",         team:"MI",  role:"BAT", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:12, name:"Devdutt Padikkal",    team:"RCB", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:13, name:"Karun Nair",          team:"DC",  role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:14, name:"Sai Sudharsan",       team:"GT",  role:"BAT", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:15, name:"Rinku Singh",         team:"KKR", role:"BAT", tier:"MARQUEE", base:150, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:16, name:"Shashank Singh",      team:"PBKS",role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:17, name:"Nehal Wadhera",       team:"PBKS",role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:18, name:"Angkrish Raghuvanshi",team:"KKR", role:"BAT", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:19, name:"Vaibhav Suryavanshi", team:"RR",  role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:20, name:"Prithvi Shaw",        team:"DC",  role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:21, name:"Ajinkya Rahane",      team:"KKR", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:22, name:"Manish Pandey",       team:"KKR", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:23, name:"Himmat Singh",        team:"LSG", role:"BAT", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:24, name:"Rovman Powell",       team:"KKR", role:"BAT", tier:"MID",     base:100, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:25, name:"Shimron Hetmyer",     team:"RR",  role:"BAT", tier:"MID",     base:100, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:26, name:"Tim David",           team:"RCB", role:"BAT", tier:"MID",     base:120, nat:"SGP", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:27, name:"Dewald Brevis",       team:"CSK", role:"BAT", tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:28, name:"Ayush Mhatre",        team:"CSK", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:29, name:"Sarfaraz Khan",       team:"CSK", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:30, name:"David Miller",        team:"DC",  role:"BAT", tier:"MID",     base:120, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:31, name:"Ben Duckett",         team:"DC",  role:"BAT", tier:"MID",     base:120, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:32, name:"Pathum Nissanka",     team:"DC",  role:"BAT", tier:"MID",     base:100, nat:"SL",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:33, name:"Aiden Markram",       team:"LSG", role:"BAT", tier:"MID",     base:120, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:34, name:"Matthew Breetzke",    team:"LSG", role:"BAT", tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:35, name:"Priyansh Arya",       team:"PBKS",role:"BAT", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:36, name:"Shahrukh Khan",       team:"GT",  role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:37, name:"Nitish Rana",         team:"DC",  role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:38, name:"Musheer Khan",        team:"PBKS",role:"BAT", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:39, name:"Finn Allen",          team:"KKR", role:"BAT", tier:"MID",     base:100, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:40, name:"Rahul Tripathi",      team:"KKR", role:"BAT", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},

  // ── WICKET-KEEPERS ───────────────────────────────────────
  {id:50, name:"Rishabh Pant",        team:"LSG", role:"WK",  tier:"MARQUEE", base:300, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:51, name:"MS Dhoni",            team:"CSK", role:"WK",  tier:"MARQUEE", base:250, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:52, name:"Sanju Samson",        team:"CSK", role:"WK",  tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:53, name:"KL Rahul",            team:"DC",  role:"WK",  tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:54, name:"Ishan Kishan",        team:"SRH", role:"WK",  tier:"MARQUEE", base:150, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:55, name:"Heinrich Klaasen",    team:"SRH", role:"WK",  tier:"MARQUEE", base:180, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:56, name:"Jos Buttler",         team:"GT",  role:"WK",  tier:"MARQUEE", base:200, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:57, name:"Phil Salt",           team:"RCB", role:"WK",  tier:"MID",     base:120, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:58, name:"Quinton de Kock",     team:"MI",  role:"WK",  tier:"MID",     base:120, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:59, name:"Ryan Rickelton",      team:"MI",  role:"WK",  tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:60, name:"Nicholas Pooran",     team:"LSG", role:"WK",  tier:"MID",     base:120, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:61, name:"Dhruv Jurel",         team:"RR",  role:"WK",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:62, name:"Josh Inglis",         team:"LSG", role:"WK",  tier:"MID",     base:100, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:63, name:"Jitesh Sharma",       team:"RCB", role:"WK",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:64, name:"Abishek Porel",       team:"DC",  role:"WK",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:65, name:"Tristan Stubbs",      team:"DC",  role:"WK",  tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:66, name:"Kumar Kushagra",      team:"GT",  role:"WK",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:67, name:"Robin Minz",          team:"MI",  role:"WK",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:68, name:"Prabhsimran Singh",   team:"PBKS",role:"WK",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},

  // ── ALL-ROUNDERS ─────────────────────────────────────────
  {id:100,name:"Hardik Pandya",       team:"MI",  role:"AR",  tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:101,name:"Ravindra Jadeja",     team:"RR",  role:"AR",  tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:102,name:"Sunil Narine",        team:"KKR", role:"AR",  tier:"MARQUEE", base:200, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:103,name:"Rashid Khan",         team:"GT",  role:"AR",  tier:"MARQUEE", base:250, nat:"AFG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:104,name:"Axar Patel",          team:"DC",  role:"AR",  tier:"MARQUEE", base:180, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:105,name:"Cameron Green",       team:"KKR", role:"AR",  tier:"MARQUEE", base:200, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:106,name:"Nitish Kumar Reddy",  team:"SRH", role:"AR",  tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:107,name:"Abhishek Sharma",     team:"SRH", role:"AR",  tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:108,name:"Mitchell Marsh",      team:"LSG", role:"AR",  tier:"MARQUEE", base:150, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:109,name:"Shivam Dube",         team:"CSK", role:"AR",  tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:110,name:"Krunal Pandya",       team:"RCB", role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:111,name:"Washington Sundar",   team:"GT",  role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:112,name:"Rachin Ravindra",     team:"KKR", role:"AR",  tier:"MID",     base:120, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:113,name:"Marco Jansen",        team:"PBKS",role:"AR",  tier:"MID",     base:120, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:114,name:"Sam Curran",          team:"RR",  role:"AR",  tier:"MID",     base:120, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:115,name:"Wanindu Hasaranga",   team:"LSG", role:"AR",  tier:"MID",     base:120, nat:"SL",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:116,name:"Jacob Bethell",       team:"RCB", role:"AR",  tier:"MID",     base:100, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:117,name:"Liam Livingstone",    team:"SRH", role:"AR",  tier:"MID",     base:120, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:118,name:"Marcus Stoinis",      team:"PBKS",role:"AR",  tier:"MID",     base:120, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:119,name:"Abdul Samad",         team:"LSG", role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:120,name:"Shahbaz Ahmed",       team:"LSG", role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:121,name:"Kamindu Mendis",      team:"SRH", role:"AR",  tier:"MID",     base:100, nat:"SL",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:122,name:"Romario Shepherd",    team:"RCB", role:"AR",  tier:"MID",     base:100, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:123,name:"Ramandeep Singh",     team:"KKR", role:"AR",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:124,name:"Venkatesh Iyer",      team:"RCB", role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:125,name:"Rahul Tewatia",       team:"GT",  role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:126,name:"Harpreet Brar",       team:"PBKS",role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:127,name:"Azmatullah Omarzai",  team:"PBKS",role:"AR",  tier:"MID",     base:100, nat:"AFG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:128,name:"Shardul Thakur",      team:"MI",  role:"AR",  tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:129,name:"Will Jacks",          team:"MI",  role:"AR",  tier:"MID",     base:100, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:130,name:"Jason Holder",        team:"GT",  role:"AR",  tier:"MID",     base:100, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:131,name:"Nishant Sindhu",      team:"GT",  role:"AR",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:132,name:"Anshul Kamboj",       team:"CSK", role:"AR",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:133,name:"Raj Angad Bawa",      team:"MI",  role:"AR",  tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:134,name:"Mitch Owen",          team:"PBKS",role:"AR",  tier:"MID",     base:100, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},
  {id:135,name:"Cooper Connolly",     team:"PBKS",role:"AR",  tier:"MID",     base:100, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, active:true},

  // ── FAST BOWLERS ─────────────────────────────────────────
  {id:200,name:"Jasprit Bumrah",      team:"MI",  role:"BOWL_FAST", tier:"MARQUEE", base:250, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:201,name:"Mitchell Starc",      team:"DC",  role:"BOWL_FAST", tier:"MARQUEE", base:200, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:202,name:"Pat Cummins",         team:"SRH", role:"BOWL_FAST", tier:"MARQUEE", base:200, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:203,name:"Kagiso Rabada",       team:"GT",  role:"BOWL_FAST", tier:"MARQUEE", base:180, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:204,name:"Mohammed Siraj",      team:"GT",  role:"BOWL_FAST", tier:"MARQUEE", base:180, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:205,name:"Jofra Archer",        team:"RR",  role:"BOWL_FAST", tier:"MARQUEE", base:200, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:206,name:"Arshdeep Singh",      team:"PBKS",role:"BOWL_FAST", tier:"MARQUEE", base:180, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:207,name:"Matheesha Pathirana", team:"KKR", role:"BOWL_FAST", tier:"MARQUEE", base:180, nat:"SL",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:208,name:"Trent Boult",         team:"MI",  role:"BOWL_FAST", tier:"MID",     base:120, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:209,name:"Bhuvneshwar Kumar",   team:"RCB", role:"BOWL_FAST", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:210,name:"Prasidh Krishna",     team:"GT",  role:"BOWL_FAST", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:211,name:"Mohammad Shami",      team:"LSG", role:"BOWL_FAST", tier:"MARQUEE", base:200, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:212,name:"Mayank Yadav",        team:"LSG", role:"BOWL_FAST", tier:"MID",     base:120, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:213,name:"Anrich Nortje",       team:"LSG", role:"BOWL_FAST", tier:"MID",     base:120, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:214,name:"T. Natarajan",        team:"DC",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:215,name:"Akash Deep",          team:"KKR", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:216,name:"Harshit Rana",        team:"KKR", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:217,name:"Vaibhav Arora",       team:"KKR", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:218,name:"Avesh Khan",          team:"LSG", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:219,name:"Harshal Patel",       team:"SRH", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:220,name:"Mukesh Kumar",        team:"DC",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:221,name:"Lungi Ngidi",         team:"DC",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:222,name:"Kyle Jamieson",       team:"DC",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:223,name:"Deepak Chahar",       team:"MI",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:224,name:"Josh Hazlewood",      team:"RCB", role:"BOWL_FAST", tier:"MID",     base:120, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:225,name:"Yash Dayal",          team:"RCB", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:226,name:"Tushar Deshpande",    team:"RR",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:227,name:"Khaleel Ahmed",       team:"CSK", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:228,name:"Nathan Ellis",        team:"CSK", role:"BOWL_FAST", tier:"MID",     base:100, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:229,name:"Lockie Ferguson",     team:"PBKS",role:"BOWL_FAST", tier:"MID",     base:100, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:230,name:"Umran Malik",         team:"KKR", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:231,name:"Shivam Mavi",         team:"SRH", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:232,name:"Jaydev Unadkat",      team:"SRH", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:233,name:"Brydon Carse",        team:"SRH", role:"BOWL_FAST", tier:"MID",     base:100, nat:"ENG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:234,name:"Nandre Burger",       team:"RR",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"SA",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:235,name:"Adam Milne",          team:"RR",  role:"BOWL_FAST", tier:"MID",     base:100, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:236,name:"Mohsin Khan",         team:"LSG", role:"BOWL_FAST", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:237,name:"Xavier Bartlett",     team:"PBKS",role:"BOWL_FAST", tier:"MID",     base:100, nat:"AUS", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:238,name:"Nuwan Thushara",      team:"RCB", role:"BOWL_FAST", tier:"MID",     base:100, nat:"SL",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:239,name:"Blessing Muzarabani", team:"KKR", role:"BOWL_FAST", tier:"MID",     base:100, nat:"ZIM", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},

  // ── SPIN BOWLERS ─────────────────────────────────────────
  {id:300,name:"Yuzvendra Chahal",    team:"PBKS",role:"BOWL_SPIN", tier:"MARQUEE", base:150, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:301,name:"Kuldeep Yadav",       team:"DC",  role:"BOWL_SPIN", tier:"MARQUEE", base:150, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:302,name:"Varun Chakravarthy",  team:"KKR", role:"BOWL_SPIN", tier:"MARQUEE", base:150, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:303,name:"Noor Ahmad",          team:"CSK", role:"BOWL_SPIN", tier:"MID",     base:120, nat:"AFG", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:304,name:"Ravi Bishnoi",        team:"RR",  role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:305,name:"Rahul Chahar",        team:"CSK", role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:306,name:"Shreyas Gopal",       team:"CSK", role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:307,name:"Mayank Markande",     team:"MI",  role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:308,name:"Suyash Sharma",       team:"RCB", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:309,name:"Zeeshan Ansari",      team:"SRH", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:310,name:"Manimaran Siddharth", team:"LSG", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:311,name:"Digvesh Singh",       team:"LSG", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:312,name:"Vicky Ostwal",        team:"RCB", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:313,name:"Sai Kishore",         team:"GT",  role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:314,name:"Jayant Yadav",        team:"GT",  role:"BOWL_SPIN", tier:"MID",     base:100, nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:315,name:"Mitchell Santner",    team:"MI",  role:"BOWL_SPIN", tier:"MID",     base:100, nat:"NZ",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:316,name:"Akeal Hosein",        team:"CSK", role:"BOWL_SPIN", tier:"MID",     base:100, nat:"WI",  runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:317,name:"Harshit Rana (Spin)", team:"KKR", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:false},
  {id:318,name:"Pravin Dubey",        team:"PBKS",role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
  {id:319,name:"Arshin Kulkarni",     team:"LSG", role:"BOWL_SPIN", tier:"UNCAPPED",base:50,  nat:"IND", runs:0, wkts:0, fours:0, sixes:0, catches:0, sr:0, dots:0, econ:0, bowlAvg:0, active:true},
];

// Filter only active players
const PLAYERS = PLAYER_DB.filter(p => p.active);

// Last year squads for RTM
const LAST_YEAR_SQUADS = {
  'The Indian Super Kings': ['Abhishek Sharma','Mitchell Marsh','Shubman Gill','Ryan Rickelton','Will Jacks','Shreyas Iyer','Ishan Kishan','Ravindra Jadeja','Matheesha Pathirana','Mitchell Santner','Mohammed Siraj','Mitchell Starc'],
  'Pocket Aces': ['Rishabh Pant','Suryakumar Yadav','Marcus Stoinis','Tilak Varma','Tristan Stubbs','Riyan Parag','MS Dhoni','Washington Sundar','Ravi Bishnoi','Pat Cummins','Trent Boult'],
  'Jhakaas XI': ['Sanju Samson','Yashasvi Jaiswal','Rohit Sharma','Aiden Markram','Shivam Dube','Rashid Khan','Rahul Tewatia','Jasprit Bumrah','Khaleel Ahmed','Deepak Chahar','Avesh Khan'],
  'The Finishers': ['Sunil Narine','Virat Kohli','Prabhsimran Singh','Rinku Singh','Heinrich Klaasen','Shashank Singh','Hardik Pandya','Nitish Kumar Reddy','Noor Ahmad','Kuldeep Yadav','Yash Dayal'],
  'Dream Team': ['Travis Head','Harshal Patel','Jos Buttler','KL Rahul','Dhruv Jurel','David Miller','Shimron Hetmyer','Rachin Ravindra','Sam Curran','Jofra Archer','Prasidh Krishna'],
  'Clutch Kings': ['Phil Salt','Varun Chakravarthy','Nicholas Pooran','Sai Sudharsan','Abishek Porel','Marco Jansen','Yuzvendra Chahal','Arshdeep Singh','Bhuvneshwar Kumar']
};

const IPL_TEAMS = {CSK:'Chennai Super Kings',MI:'Mumbai Indians',RCB:'Royal Challengers Bengaluru',KKR:'Kolkata Knight Riders',SRH:'Sunrisers Hyderabad',DC:'Delhi Capitals',LSG:'Lucknow Super Giants',RR:'Rajasthan Royals',GT:'Gujarat Titans',PBKS:'Punjab Kings'};

const OFFICE_TEAMS = [
  {id:1, name:'The Indian Super Kings', members:'Yatharth, Prashant, Dipesh',   type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['The Indian Super Kings']},
  {id:2, name:'Pocket Aces',            members:'Anush, Tarun, Himanshu',        type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['Pocket Aces']},
  {id:3, name:'Jhakaas XI',             members:'Ramesh, Shreyans, Ashish',      type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['Jhakaas XI']},
  {id:4, name:'The Finishers',          members:'Purva, Arpit, Aditya',          type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['The Finishers']},
  {id:5, name:'Dream Team',             members:'Yash, Jay, Ashish Teli',        type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['Dream Team']},
  {id:6, name:'Clutch Kings',           members:'Gursimrat, Kushagra',           type:'returning', rtmLeft:2, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad: LAST_YEAR_SQUADS['Clutch Kings']},
  {id:7, name:'Wonder Women',           members:'Sharon, Vidya, Mini, Namita',   type:'wonder_women', rtmLeft:3, points:3000, squad:[], matchPts:0, bonusPts:0, lastYearSquad:[]},
];
